// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibrary():Promise<boolean>;

export function GetActiveLibrary():Promise<string>;

export function GetBandizipPath():Promise<string>;

export function GetEHentaiCookie():Promise<string>;

export function GetKemonoCookie():Promise<string>;

export function GetKemonoUseOriginalImages():Promise<boolean>;

export function GetJmCacheDir():Promise<string>;

export function GetJmCacheRetentionHours():Promise<number>;

export function GetJmCacheSizeLimitMB():Promise<number>;

export function GetLibraries():Promise<Array<string>>;

export function GetOutputDir():Promise<string>;

export function GetProxy():Promise<string>;

export function GetSourceRepoURL():Promise<string>;

export function SetActiveLibrary(arg1:string):Promise<boolean>;

export function SetBandizipPath(arg1:string):Promise<boolean>;

export function SetEHentaiCookie(arg1:string):Promise<boolean>;

export function SetKemonoCookie(arg1:string):Promise<boolean>;

export function SetKemonoUseOriginalImages(arg1:boolean):Promise<boolean>;

export function SetJmCacheDir(arg1:string):Promise<boolean>;

export function SetJmCacheRetentionHours(arg1:number):Promise<boolean>;

export function SetJmCacheSizeLimitMB(arg1:number):Promise<boolean>;

export function SetOutputDir():Promise<boolean>;

export function SetProxy(arg1:string):Promise<boolean>;

export function SetSourceRepoURL(arg1:string):Promise<boolean>;
