// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddLibrary() {
  return window['go']['config']['API']['AddLibrary']();
}

export function GetActiveLibrary() {
  return window['go']['config']['API']['GetActiveLibrary']();
}

export function GetBandizipPath() {
  return window['go']['config']['API']['GetBandizipPath']();
}

export function GetEHentaiCookie() {
  return window['go']['config']['API']['GetEHentaiCookie']();
}

export function GetKemonoCookie() {
  return window['go']['config']['API']['GetKemonoCookie']();
}

export function GetKemonoUseOriginalImages() {
  return window['go']['config']['API']['GetKemonoUseOriginalImages']();
}

export function GetJmCacheDir() {
  return window['go']['config']['API']['GetJmCacheDir']();
}

export function GetJmCacheRetentionHours() {
  return window['go']['config']['API']['GetJmCacheRetentionHours']();
}

export function GetJmCacheSizeLimitMB() {
  return window['go']['config']['API']['GetJmCacheSizeLimitMB']();
}

export function GetLibraries() {
  return window['go']['config']['API']['GetLibraries']();
}

export function GetOutputDir() {
  return window['go']['config']['API']['GetOutputDir']();
}

export function GetProxy() {
  return window['go']['config']['API']['GetProxy']();
}

export function GetSourceRepoURL() {
  return window['go']['config']['API']['GetSourceRepoURL']();
}

export function SetActiveLibrary(arg1) {
  return window['go']['config']['API']['SetActiveLibrary'](arg1);
}

export function SetBandizipPath(arg1) {
  return window['go']['config']['API']['SetBandizipPath'](arg1);
}

export function SetEHentaiCookie(arg1) {
  return window['go']['config']['API']['SetEHentaiCookie'](arg1);
}

export function SetKemonoCookie(arg1) {
  return window['go']['config']['API']['SetKemonoCookie'](arg1);
}

export function SetKemonoUseOriginalImages(arg1) {
  return window['go']['config']['API']['SetKemonoUseOriginalImages'](arg1);
}

export function SetJmCacheDir(arg1) {
  return window['go']['config']['API']['SetJmCacheDir'](arg1);
}

export function SetJmCacheRetentionHours(arg1) {
  return window['go']['config']['API']['SetJmCacheRetentionHours'](arg1);
}

export function SetJmCacheSizeLimitMB(arg1) {
  return window['go']['config']['API']['SetJmCacheSizeLimitMB'](arg1);
}

export function SetOutputDir() {
  return window['go']['config']['API']['SetOutputDir']();
}

export function SetProxy(arg1) {
  return window['go']['config']['API']['SetProxy'](arg1);
}

export function SetSourceRepoURL(arg1) {
  return window['go']['config']['API']['SetSourceRepoURL'](arg1);
}
